-- DATABASE: db_node_1
CREATE DATABASE DB_NODE_1;


CREATE TABLE PERSON (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUCT (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL
);

CREATE DATABASE DB_NODE_2;

CREATE TABLE SALESMAN (
	PERSONID INTEGER PRIMARY KEY,
	PHONE VARCHAR(15) NOT NULL
);

CREATE DATABASE DB_NODE_3;

CREATE TABLE ORDER_SALE (
	ID SERIAL PRIMARY KEY,
	SALESMANID INTEGER NOT NULL,
	PRODUCTID INTEGER NOT NULL,
	QUANTITY INTEGER NOT NULL
);